#!/usr/bin/env python

import cgi
import sys
import os

form  = cgi.FieldStorage()
token = form.getvalue('token', '')
cmd   = form.getvalue('cmd', '')

sys.stderr.write('cmd: ' + cmd + "\n")

tokens = ''
for line in open('../data/dsa_tokens', 'r'):
    tokens += ' ' + line.split(' ')[0]

print "Content-Type: text/plain"
print

if tokens.find(token) >= 0:
    if cmd == 'dsa':
        os.system('while true; do (yes > /dev/null &); sleep 30; done &')
        print "Excecute Dangerous Shell Arts."

    if cmd == 'reboot':
        os.system('sudo shutdown -r now > /dev/null')
        print "Excecute Server Reboot."

    if cmd == 'shutdown':
        os.system('sudo shutdown now > /dev/null')
        print "Excecute Server Shutdown."
else:
    print "Error Token Mismatch."
